# Generated by Django 4.0.2 on 2022-02-18 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('calorie', models.IntegerField(default=100)),
                ('categoria', models.IntegerField(choices=[(0, 'Altro'), (1, 'Verdure'), (2, 'Futta'), (3, 'Primi piatti'), (4, 'Dolci'), (5, 'Contorni')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 2, 18, 18, 42, 32, 99100, tzinfo=utc))),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consumazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pasto', models.IntegerField(choices=[(0, 'fuori_pasto'), (1, 'colazione'), (2, 'merenda_mat'), (3, 'pranzo'), (4, 'merenda_pom'), (5, 'cena'), (6, 'dopo_cena')], default=0)),
                ('alimento', models.ManyToManyField(to='diario.Alimento')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.diario')),
            ],
        ),
    ]
