# Generated by Django 4.0.2 on 2022-02-25 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_alter_diario_data_consumazione_pasto_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 20, 56, 51, 356494, tzinfo=utc), unique=True),
        ),
    ]
