# Generated by Django 4.0.2 on 2022-02-25 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_alter_diario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 21, 19, 26, 830673, tzinfo=utc), unique=True),
        ),
    ]
