# Generated by Django 4.0.2 on 2022-02-25 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_diario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateField(default=datetime.date(2022, 2, 25), unique=True),
        ),
    ]
