# Generated by Django 3.2.11 on 2022-03-19 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_auto_20220314_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateField(default=datetime.date(2022, 3, 19), unique=True),
        ),
    ]
