# Generated by Django 3.2.11 on 2022-03-20 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_auto_20220319_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateField(default=datetime.date(2022, 3, 20), unique=True),
        ),
    ]
