# Generated by Django 3.2.11 on 2022-04-01 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_alter_diario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Altro'), (1, 'Latticini'), (2, 'Cereali'), (3, 'Pane'), (4, 'Pasta'), (5, 'Carni'), (6, 'Legumi'), (7, 'Dolci'), (8, 'Patate'), (9, 'Bevande'), (10, 'Pesce'), (11, 'Frutta'), (12, 'Verdure'), (13, 'Riso'), (14, 'Uova'), (15, 'Pane e Pizza'), (16, 'Formaggi'), (17, 'Insaccati')], default=0),
        ),
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateField(default=datetime.date(2022, 4, 1), unique=True),
        ),
    ]
