# Generated by Django 3.2.11 on 2022-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_auto_20220401_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Altro'), (9, 'Bevande'), (5, 'Carni'), (2, 'Cereali'), (7, 'Dolci'), (16, 'Formaggi'), (11, 'Frutta'), (17, 'Insaccati'), (1, 'Latticini'), (6, 'Legumi'), (3, 'Pane'), (15, 'Pane e Pizza'), (4, 'Pasta'), (8, 'Patate'), (10, 'Pesce'), (13, 'Riso'), (14, 'Uova'), (12, 'Verdure')], default=0),
        ),
    ]
