# Generated by Django 3.2.11 on 2022-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0002_aziende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aziende',
            name='tutor_referente_azienda',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
