# Generated by Django 3.2.11 on 2022-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0003_alter_aziende_tutor_referente_azienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aziende',
            name='tutor_referente_azienda',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
