# Generated by Django 3.2.11 on 2022-04-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0006_alter_aziende_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aziende',
        ),
    ]
