# Generated by Django 3.2.11 on 2022-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0008_aziende'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aziende',
            name='partita_iva',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='sede_comune',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='sede_provincia',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='settore',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='tutor_referente_azienda',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
