# Generated by Django 3.2.11 on 2022-04-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0009_auto_20220414_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aziende',
            options={'ordering': ['ragione_sociale']},
        ),
        migrations.AddField(
            model_name='aziende',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
