# Generated by Django 3.2.11 on 2022-04-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffPcto', '0010_auto_20220415_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aziende',
            name='score',
        ),
        migrations.AddField(
            model_name='tutor',
            name='classi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
