# Generated by Django 4.0.2 on 2023-10-31 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aziende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivio', models.CharField(blank=True, choices=[('R', 'Ristoranti'), ('H', 'Hotel'), ('G', 'Gelaterie'), ('C', 'Casse')], default='R', max_length=2, null=True)),
                ('categoria', models.CharField(max_length=150, null=True)),
                ('nome', models.CharField(max_length=250)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('indirizzo', models.CharField(max_length=300, null=True)),
                ('citta', models.CharField(blank=True, max_length=200, null=True)),
                ('cap', models.CharField(max_length=6, null=True)),
                ('provincia', models.CharField(blank=True, max_length=4, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.EmailField(blank=True, max_length=200, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('num_immagini', models.IntegerField(default=0)),
                ('servizi', models.TextField(blank=True, null=True)),
                ('altri_servizi', models.TextField(blank=True, null=True)),
                ('google_map', models.TextField(blank=True, max_length=300, null=True)),
                ('orari', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['archivio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RichiesteContatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('interessi', models.IntegerField(choices=[(1, 'Comande'), (2, 'Prenotazioni'), (3, 'Menù digitale'), (4, 'Sito web'), (5, 'Tutto')], default=4)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('evidenziato', models.BooleanField(default=False)),
                ('da_chiamare', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatti.agenti')),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contatti.aziende')),
            ],
            options={
                'ordering': ['-evidenziato', '-data'],
            },
        ),
    ]
