# Generated by Django 4.0.2 on 2023-11-01 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestecontatti',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='richiestecontatti',
            name='interessi',
            field=models.IntegerField(choices=[(1, 'Comande'), (2, 'Prenotazioni'), (3, 'Menù digitale'), (4, 'Sito web'), (5, 'Tutto')], default=5),
        ),
    ]
