# Generated by Django 4.1.1 on 2023-01-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aziende',
            name='altri_servizi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='google_map',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='orari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='servizi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
