# Generated by Django 4.1.1 on 2023-01-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0003_alter_aziende_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aziende',
            name='archivio',
            field=models.CharField(blank=True, choices=[('R', 'Ristoranti'), ('H', 'Hotel')], default='R', max_length=2, null=True),
        ),
    ]
