# Generated by Django 4.1.1 on 2023-01-03 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0005_agenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatti.agenti')),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contatti.aziende')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
