# Generated by Django 3.2 on 2023-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatti', '0009_alter_contatti_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatti',
            name='da_chimare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='archivio',
            field=models.CharField(blank=True, choices=[('R', 'Ristoranti'), ('H', 'Hotel'), ('G', 'Gelaterie'), ('C', 'Casse')], default='R', max_length=2, null=True),
        ),
    ]
