# Generated by Django 4.1.1 on 2023-01-01 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('calorie', models.IntegerField(default=100)),
                ('categoria', models.IntegerField(choices=[(0, 'Altro'), (9, 'Bevande'), (5, 'Carni'), (2, 'Cereali'), (7, 'Dolci'), (16, 'Formaggi'), (11, 'Frutta'), (17, 'Insaccati'), (1, 'Latticini'), (6, 'Legumi'), (3, 'Pane'), (15, 'Pane e Pizza'), (4, 'Pasta'), (8, 'Patate'), (10, 'Pesce'), (13, 'Riso'), (14, 'Uova'), (12, 'Verdure')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date(2023, 1, 1), unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consumazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pasto', models.IntegerField(choices=[(0, 'fuori_pasto'), (1, 'colazione'), (2, 'merenda_mat'), (3, 'pranzo'), (4, 'merenda_pom'), (5, 'cena'), (6, 'dopo_cena'), (7, 'Movimento')], default=0)),
                ('acque', models.IntegerField(default=1)),
                ('quantita_extra', models.BooleanField(default=False)),
                ('alimento', models.ManyToManyField(to='giulio.alimento')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giulio.diario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consumazione',
            constraint=models.UniqueConstraint(fields=('tipo_pasto', 'diario'), name='meal_unique'),
        ),
    ]
